server:
  port: 19527

spring:
  application:
    name: metro-backend

  jackson:
    generator:
      write_numbers_as_strings: true
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # 取消静态资源映射 并向上抛出404
  # resources:
  # add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

  profiles:
    active: dev
